### ISSUE TITLE
Create an Index Template for Sharding

### ISSUE THREAD

**Issue by ajpahl1008** [ajpahl1008/simple-data-generator#13]
Currently SDG only creates a single primary and replica shard (the defaults in Elasticsearch 8).
For each workload (and index defined) this feature will: 

- add primary and replica shard configurations to an index template
- delete/recreate the template on test initiation (not-optional)

Proposed configurations for workloads: 
```

workloads:
  - workloadName: workload_1
    workloadThreads: 1
    workloadSleep: 1000
    indexName: index-1
    primaryShardCount: 1   <-- New Configuration
    replicaShardCount: 1     <-- New Configuration
    fields:
      - name: account_number
        type: int

      - name: state
        type: state

      - name: balance
        type: float
        range: 1,20000
```
